import { useState, useRef, useEffect } from 'react'
import { useParams, useNavigate, useLocation } from 'react-router-dom'
import { useSuperAgents } from '../store/superAgentStore.jsx'
import './AgentWebUI.css'

export default function AgentWebUI() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { agents, dispatch } = useSuperAgents()
  const agent = agents.find(a => a.id === id)

  const location = useLocation()
  const searchParams = new URLSearchParams(location.search)
  const initialView = searchParams.get('view') === 'cron' ? 'cron' : 'chat'

  const [activeView, setActiveView] = useState(initialView)
  const [activeConv, setActiveConv] = useState(null)
  const [showCronModal, setShowCronModal] = useState(false)
  const [editingCron, setEditingCron] = useState(null)
  const [popoverId, setPopoverId] = useState(null)
  const [showRunProgress, setShowRunProgress] = useState(false)
  const [runStep, setRunStep] = useState(0) // 0: Linking, 1: Running, 2: Done
  const [showWorkspace, setShowWorkspace] = useState(true)

  const [showAIGenModal, setShowAIGenModal] = useState(false)
  const [aiThinking, setAiThinking] = useState(false)
  const [aiPrompt, setAiPrompt] = useState('')
  const [generatedSkill, setGeneratedSkill] = useState(null)

  // Action Menu State (formerly Context Menu)
  const [activeActionItem, setActiveActionItem] = useState(null) // { id: '...', type: 'file'/'folder', x, y }
  
  // Artifacts State
  const [artifacts, setArtifacts] = useState([
    { id: 'art-1', name: '数据分析报告', description: '基于 Q1 销售数据的自动化分析结果', versions: [
      { id: 'v2', version: 'v1.1.0', file: 'report_v1.1.pdf', time: '2026-04-05 14:20' },
      { id: 'v1', version: 'v1.0.0', file: 'report_v1.0.pdf', time: '2026-04-01 09:00' }
    ]},
    { id: 'art-2', name: '清洗后的数据集', description: '去除缺失值并完成归一化处理的数据', versions: [
      { id: 'v1', version: 'v1.0.0', file: 'clean_data.csv', time: '2026-04-06 11:30' }
    ]}
  ]);
  const [showArtifactLinkModal, setShowArtifactLinkModal] = useState(false);
  const [linkFile, setLinkFile] = useState(null);
  const [expandedArtifacts, setExpandedArtifacts] = useState(new Set());
  
  const [inputText, setInputText] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const [fileNames, setFileNames] = useState([])
  const chatEndRef = useRef(null)
  const fileInputRef = useRef(null)

  // Global click to close menu
  useEffect(() => {
    const handleClick = () => setActiveActionItem(null);
    window.addEventListener('click', handleClick);
    return () => window.removeEventListener('click', handleClick);
  }, []);

  const handleActionClick = (e, type, item) => {
    e.stopPropagation();
    const rect = e.currentTarget.getBoundingClientRect();
    setActiveActionItem({
      x: rect.left - 180, 
      y: rect.bottom + 8,
      visible: true,
      type,
      item
    });
  };

  const toggleArtifactExpand = (id) => {
    const next = new Set(expandedArtifacts);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setExpandedArtifacts(next);
  };

  const handleAIGen = () => {
    if (!aiPrompt.trim()) return
    setAiThinking(true)
    setGeneratedSkill(null)
    
    setTimeout(() => {
      setAiThinking(false)
      setGeneratedSkill({
        id: `skill-${Date.now()}`,
        name: aiPrompt.includes('金价') ? 'GoldPriceTracker' : 'CustomTool',
        description: `基于您的需求生成的技能: ${aiPrompt}`,
        icon: aiPrompt.includes('金价') ? '💰' : '🛠️',
        code: `def execute(params):\n    # Generated by AI\n    print("Fetching data for: ${aiPrompt}")\n    return {"status": "success", "data": "Sample result"}`
      })
    }, 2500)
  }

  const addGeneratedSkill = () => {
    if (!generatedSkill) return
    dispatch({
      type: 'UPDATE_AGENT',
      id: agent.id,
      updates: { skills: [...(agent.skills || []), generatedSkill.name] }
    })
    setShowAIGenModal(false)
    setGeneratedSkill(null)
    setAiPrompt('')
  }

  const handleRunNow = () => {
    setPopoverId(null)
    setShowRunProgress(true)
    setRunStep(0)
    
    // Simulate steps
    setTimeout(() => setRunStep(1), 1500)
    setTimeout(() => setRunStep(2), 3500)
    setTimeout(() => {
      setShowRunProgress(false)
      setActiveView('chat')
      // Optional: Add a system message to the chat
    }, 5000)
  }

  // Initialize with first conversation
  useEffect(() => {
    if (agent && agent.conversations?.length > 0 && !activeConv) {
      setActiveConv(agent.conversations[0].id)
    }
  }, [agent])

  // Scroll to bottom on new messages
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [activeConv, agent?.conversations])

  if (!agent) {
    return (
      <div className="webui-not-found">
        <div>Agent 不存在</div>
        <button className="action-btn primary" onClick={() => navigate('/super-agent')}>返回列表</button>
      </div>
    )
  }

  const conversations = agent.conversations || []
  const currentConv = conversations.find(c => c.id === activeConv)

  const createConversation = () => {
    const newConv = {
      id: `conv-${Date.now()}`,
      title: '新任务',
      createdAt: new Date().toISOString().replace('T', ' ').slice(0, 19),
      messages: [],
    }
    dispatch({ type: 'ADD_CONVERSATION', id: agent.id, conversation: newConv })
    setActiveConv(newConv.id)
  }

  const sendMessage = () => {
    if (!inputText.trim() && fileNames.length === 0) return
    if (!activeConv) {
      // Create new conversation first
      const newConv = {
        id: `conv-${Date.now()}`,
        title: inputText.trim().slice(0, 20) || '新任务',
        createdAt: new Date().toISOString().replace('T', ' ').slice(0, 19),
        messages: [],
      }
      dispatch({ type: 'ADD_CONVERSATION', id: agent.id, conversation: newConv })
      setActiveConv(newConv.id)
      // Send in next tick
      setTimeout(() => doSend(newConv.id), 50)
      return
    }
    doSend(activeConv)
  }

  const doSend = (convId) => {
    const now = new Date().toISOString().replace('T', ' ').slice(0, 19)
    let content = inputText.trim()
    if (fileNames.length > 0) {
      content += `\n📎 附件: ${fileNames.join(', ')}`
    }

    // Add user message
    dispatch({
      type: 'ADD_MESSAGE',
      agentId: agent.id,
      convId,
      message: { role: 'user', content, time: now },
    })
    setInputText('')
    setFileNames([])
    setIsTyping(true)

    // Simulate tool calls + response
    setTimeout(() => {
      const skillsUsed = agent.skills.slice(0, Math.min(2, agent.skills.length))
      const toolLog = skillsUsed.map(s => `🔧 调用 ${s} … 执行完成`).join('\n')
      if (toolLog) {
        dispatch({
          type: 'ADD_MESSAGE',
          agentId: agent.id,
          convId,
          message: { role: 'tool', content: toolLog, time: now },
        })
      }

      setTimeout(() => {
        const responses = [
          `根据您的请求，我已完成分析。以下是处理结果：\n\n1. 已从数据源获取相关信息\n2. 完成内容整理与摘要\n3. 结果已保存至工作区\n\n如需进一步处理，请告诉我。`,
          `任务已完成 ✅\n\n### 处理摘要\n- 输入分析完毕\n- 调用了 ${skillsUsed.join('、')} 等能力\n- 耗时约 ${Math.floor(Math.random() * 20 + 5)} 秒\n\n是否需要对结果进行调整？`,
          `我已经处理了您的请求。\n\n**关键发现：**\n- 检测到 ${Math.floor(Math.random() * 10 + 3)} 个相关条目\n- 数据质量评分: ${(Math.random() * 20 + 80).toFixed(1)}%\n- 已生成结构化输出\n\n请查看工作区中的输出文件。`,
        ]
        dispatch({
          type: 'ADD_MESSAGE',
          agentId: agent.id,
          convId,
          message: { role: 'assistant', content: responses[Math.floor(Math.random() * responses.length)], time: now },
        })
        setIsTyping(false)
      }, 1200)
    }, 800)
  }

  const handleFileSelect = (e) => {
    const files = Array.from(e.target.files)
    setFileNames(prev => [...prev, ...files.map(f => f.name)])
    e.target.value = ''
  }

  const removeFile = (name) => {
    setFileNames(prev => prev.filter(f => f !== name))
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  // Render file tree recursively
  const renderFileTree = (items, depth = 0) => {
    return items.map((item, i) => (
      <div key={i}>
        <div 
          className="webui-file-item file-tree-row" 
          style={{ paddingLeft: depth * 16 + 12 }}
        >
          <span className="webui-file-icon">{item.type === 'folder' ? (depth < 2 ? '📂' : '📁') : '📄'}</span>
          <span className="webui-file-name">{item.name}</span>
          {item.size && <span className="webui-file-size">{item.size}</span>}
          <button 
            className="row-action-btn" 
            onClick={(e) => handleActionClick(e, item.type === 'folder' ? 'folder' : 'file', item)}
          >
            ⋮
          </button>
        </div>
        {item.children && renderFileTree(item.children, depth + 1)}
      </div>
    ))
  }

  return (
    <div className="webui-page">
      {/* ========== LEFT: Conversation List ========== */}
      <div className="webui-sidebar">
        <div className="webui-sidebar-header">
          <button className="webui-back-btn" onClick={() => navigate(`/super-agent/${agent.id}`)}>← 返回</button>
          <div className="webui-agent-name">{agent.name}</div>
        </div>
        
        <div className="webui-sidebar-menu">
          <div className={`webui-menu-item ${activeView === 'chat' ? 'active' : ''}`} onClick={() => setActiveView('chat')}>💬 会话列表</div>
          <div className={`webui-menu-item ${activeView === 'skills' ? 'active' : ''}`} onClick={() => setActiveView('skills')}>🔧 技能配置</div>
          <div className={`webui-menu-item ${activeView === 'cron' ? 'active' : ''}`} onClick={() => setActiveView('cron')}>⏱️ 定时任务</div>
          <div className={`webui-menu-item ${activeView === 'artifacts' ? 'active' : ''}`} onClick={() => setActiveView('artifacts')}>📦 制品管理</div>
        </div>
        
        <div className="webui-menu-divider" />
        
        {activeView === 'chat' ? (
          <>
            <button className="webui-new-task" onClick={createConversation}>+ 新任务</button>
            <div className="webui-conv-list">
              {conversations.map(conv => (
                <div
                  key={conv.id}
                  className={`webui-conv-item ${activeConv === conv.id ? 'active' : ''}`}
                  onClick={() => setActiveConv(conv.id)}
                >
                  <div className="webui-conv-title">{conv.title}</div>
                  <div className="webui-conv-time">{conv.createdAt?.slice(5, 16)}</div>
                </div>
              ))}
              {conversations.length === 0 && (
                <div className="webui-conv-empty">暂无会话，点击上方按钮创建</div>
              )}
            </div>
          </>
        ) : (
          <div style={{ padding: '0 12px', fontSize: '13px', color: '#8c8c8c' }}>
            在这里查看和管理该 Agent 的所有定时调度任务。
          </div>
        )}
      </div>

      {/* ========== CENTER: Chat or Cron View ========== */}
      {activeView === 'chat' ? (
        <div className="webui-chat">
          <div className="webui-chat-header">
            <span className="webui-chat-title">{currentConv ? currentConv.title : '选择或创建一个会话'}</span>
            <span className="webui-model-badge">{agent.model}</span>
            <div style={{ marginLeft: 'auto', display: 'flex', gap: '8px' }}>
              <button 
                className={`action-btn small ${showWorkspace ? 'active' : ''}`} 
                onClick={() => setShowWorkspace(!showWorkspace)}
                style={{ fontSize: '12px', padding: '4px 10px' }}
              >
                {showWorkspace ? '📂 隐藏工作区' : '📁 显示工作区'}
              </button>
            </div>
          </div>

          <div className="webui-messages">
            {!currentConv ? (
              <div className="webui-welcome">
                <div className="webui-welcome-icon">🤖</div>
                <div className="webui-welcome-title">欢迎使用 {agent.name}</div>
                <div className="webui-welcome-desc">{agent.description}</div>
                <button className="action-btn primary" onClick={createConversation}>开始新对话</button>
              </div>
            ) : currentConv.messages.length === 0 ? (
              <div className="webui-welcome">
                <div className="webui-welcome-icon">💬</div>
                <div className="webui-welcome-title">开始对话</div>
                <div className="webui-welcome-desc">输入你的需求，Agent 将为你处理</div>
              </div>
            ) : (
              currentConv.messages.map((msg, i) => (
                <div key={i} className={`webui-msg webui-msg-${msg.role}`}>
                  {msg.role === 'user' && (
                    <div className="webui-msg-row webui-msg-user-row">
                      <div className="webui-msg-bubble webui-msg-user-bubble">{msg.content}</div>
                      <div className="webui-msg-avatar webui-avatar-user">U</div>
                    </div>
                  )}
                  {msg.role === 'tool' && (
                    <div className="webui-msg-row webui-msg-tool-row">
                      <div className="webui-msg-avatar webui-avatar-tool">⚙</div>
                      <div className="webui-tool-log">
                        <div className="webui-tool-header">工具执行过程</div>
                        <pre>{msg.content}</pre>
                      </div>
                    </div>
                  )}
                  {msg.role === 'assistant' && (
                    <div className="webui-msg-row webui-msg-assistant-row">
                      <div className="webui-msg-avatar webui-avatar-agent">🤖</div>
                      <div className="webui-msg-bubble webui-msg-agent-bubble">
                        {msg.content.split('\n').map((line, li) => (
                          <span key={li}>{line}<br/></span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}
            {isTyping && (
              <div className="webui-msg webui-msg-assistant">
                <div className="webui-msg-row webui-msg-assistant-row">
                  <div className="webui-msg-avatar webui-avatar-agent">🤖</div>
                  <div className="webui-typing">
                    <span /><span /><span />
                  </div>
                </div>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          <div className="webui-input-area">
            {fileNames.length > 0 && (
              <div className="webui-attached-files">
                {fileNames.map(f => (
                  <span key={f} className="webui-attached-file">📎 {f} <span className="webui-file-remove" onClick={() => removeFile(f)}>×</span></span>
                ))}
              </div>
            )}
            <div className="webui-input-row">
              <button className="webui-attach-btn" onClick={() => fileInputRef.current?.click()} title="上传文件">+</button>
              <input type="file" ref={fileInputRef} style={{display:'none'}} multiple onChange={handleFileSelect} />
              <textarea
                className="webui-textarea"
                value={inputText}
                onChange={e => setInputText(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="请输入你的需求"
                rows={1}
              />
              <button className="webui-send-btn" onClick={sendMessage} disabled={!inputText.trim() && fileNames.length === 0}>↑</button>
            </div>
          </div>
        </div>
      ) : activeView === 'cron' ? (
        <div className="cron-mgmt-content">
          <div className="cron-header-row">
            <h2 className="cron-main-title">定时任务</h2>
            <button className="cron-btn-new" onClick={() => { setEditingCron({ name: '', prompt: '', time: '10:00', days: [1,2,3,4,5], icon: '📄', schedType: 'daily' }); setShowCronModal(true); }}>
              <span>+</span> 新任务
            </button>
          </div>

          <div className="cron-template-grid">
            <div className="cron-template-card">
              <div className="cron-card-icon" style={{ background: '#f6ffed', color: '#52c41a' }}>📄</div>
              <div className="cron-card-title">每日行业资讯</div>
              <div className="cron-card-desc">每天上午 9 点 25 分，给我推送当天新语资讯...</div>
            </div>
            <div className="cron-template-card">
              <div className="cron-card-icon" style={{ background: '#e6f7ff', color: '#1890ff' }}>⏱️</div>
              <div className="cron-card-title">市场舆情追踪</div>
              <div className="cron-card-desc">每天中午 13 点 30 分，帮我搜索并汇总舆情...</div>
            </div>
            <div className="cron-template-card">
              <div className="cron-card-icon" style={{ background: '#f9f0ff', color: '#722ed1' }}>📅</div>
              <div className="cron-card-title">工作周报</div>
              <div className="cron-card-desc">每周五下午 17 点 45 分，帮我生成周报...</div>
            </div>
          </div>

          <div className="cron-list-section">
            <div className="cron-section-label">已定定时任务</div>
            <table className="cron-table">
              <thead>
                <tr>
                  <th>标题</th>
                  <th>计划执行时间</th>
                  <th>状态</th>
                  <th style={{ textAlign: 'right' }}>更多操作</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { id: 1, name: 'Agent Infra 每日情报汇总', next: '2026年4月8日 10:00', status: true },
                  { id: 2, name: '一周技术动态追踪', next: '2026年4月11日 09:00', status: true },
                  { id: 3, name: '系统资源自动清理', next: '2026年4月12日 00:00', status: false },
                ].map(item => (
                  <tr key={item.id}>
                    <td style={{ fontWeight: 500 }}>{item.name}</td>
                    <td>{item.next}</td>
                    <td>
                      <label className="cron-toggle">
                        <input type="checkbox" checked={item.status} readOnly />
                        <span className="cron-slider"></span>
                      </label>
                    </td>
                    <td style={{ textAlign: 'right', position: 'relative' }}>
                      <button className="cron-more-btn" onClick={() => setPopoverId(popoverId === item.id ? null : item.id)}>•••</button>
                      {popoverId === item.id && (
                        <div className="cron-popover">
                          <div className="popover-item" onClick={handleRunNow}>▶ 立即运行</div>
                          <div className="popover-item" onClick={() => { setEditingCron({ name: item.name, prompt: '请搜索并汇总 "agent infra" 在过去24小时内的全网最新动态...', time: '10:00', days: [1,2,3,4,5], icon: '📄', schedType: 'daily', cron: '0 0/15 * * * ?' }); setShowCronModal(true); setPopoverId(null); }}>✏️ 编辑</div>
                          <div className="popover-item danger">🗑️ 删除</div>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : activeView === 'skills' ? (
        <div className="skill-mgmt-content">
          <div className="skill-header">
            <div className="skill-header-left">
              <h2>技能配置</h2>
              <p>管理 Agent 已绑定的技能，或使用 AI 生成新技能</p>
            </div>
            <div className="skill-actions">
              <button className="action-btn" onClick={() => alert('从技能中心添加')}>+ 库添加</button>
              <button className="btn-ai-gen" onClick={() => setShowAIGenModal(true)}>✨ AI 生成技能</button>
            </div>
          </div>

          <div className="skill-grid">
            {(agent.skills || []).map((skillName, idx) => (
              <div key={idx} className="skill-card">
                <div className="skill-card-header">
                  <div className="skill-icon-box">
                    {skillName === 'web_search' ? '🔍' : skillName === 'interpreter' ? '💻' : skillName === 'file_manager' ? '📂' : '🛠️'}
                  </div>
                  <button 
                    className="btn-remove-skill" 
                    title="移除技能"
                    onClick={() => {
                      dispatch({
                        type: 'UPDATE_AGENT',
                        id: agent.id,
                        updates: { skills: agent.skills.filter(s => s !== skillName) }
                      })
                    }}
                  >
                    ×
                  </button>
                </div>
                <div className="skill-card-name">{skillName}</div>
                <div className="skill-card-desc">
                  {skillName === 'web_search' && '支持连接互联网搜索最新信息、新闻动态'}
                  {skillName === 'interpreter' && '支持运行 Python 代码，分析数据、绘制图表'}
                  {skillName === 'file_manager' && '支持读写、管理工作区内的文件'}
                  {!['web_search', 'interpreter', 'file_manager'].includes(skillName) && 'AI 自动生成的自定义技能，支持执行特定业务逻辑'}
                </div>
                <div className="skill-card-footer">
                  <span className="skill-tag">v1.2</span>
                  <span className="skill-tag">内置</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="artifacts-mgmt-content">
          <div className="artifact-info-bar">
            <div>
              <h2>制品管理</h2>
              <p style={{ color: '#999', fontSize: '14px', margin: '4px 0 0' }}>查看和维护 Agent 生成的各类数字化制品及版本</p>
            </div>
            <button className="action-btn primary" onClick={() => alert('创建新制品')}>+ 创建制品</button>
          </div>

          <table className="artifact-table">
            <thead>
              <tr>
                <th>制品名称</th>
                <th>最新版本</th>
                <th>描述</th>
                <th>更新时间</th>
                <th style={{ textAlign: 'right' }}>操作</th>
              </tr>
            </thead>
            <tbody>
              {artifacts.map(art => (
                <React.Fragment key={art.id}>
                  <tr>
                    <td>
                      <div className="artifact-name">📦 {art.name}</div>
                    </td>
                    <td>
                      <span className="artifact-version-pill">{art.versions[0]?.version}</span>
                    </td>
                    <td style={{ color: '#64748b', fontSize: '13px' }}>{art.description}</td>
                    <td style={{ color: '#94a3b8', fontSize: '13px' }}>{art.versions[0]?.time}</td>
                    <td style={{ textAlign: 'right' }}>
                      <button className="artifact-actions-btn" onClick={() => toggleArtifactExpand(art.id)}>
                        {expandedArtifacts.has(art.id) ? '收起版本' : '版本记录'}
                      </button>
                      <button className="artifact-actions-btn" style={{ marginLeft: '8px' }} onClick={() => alert('编辑制品')}>编辑</button>
                    </td>
                  </tr>
                  {expandedArtifacts.has(art.id) && (
                    <tr>
                      <td colSpan={5} style={{ padding: '0 16px 16px' }}>
                        <div className="version-list-panel">
                          {art.versions.map(v => (
                            <div key={v.id} className="version-row">
                              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                                <span style={{ fontWeight: 600, color: '#6366f1' }}>{v.version}</span>
                                <span style={{ fontSize: '12px', color: '#64748b' }}>文件: {v.file}</span>
                              </div>
                              <div style={{ display: 'flex', alignItems: 'center' }}>
                                <span style={{ fontSize: '12px', color: '#94a3b8', marginRight: '20px' }}>{v.time}</span>
                                <span className="btn-v-download" onClick={() => alert(`下载 ${v.file}`)}>下载</span>
                                <span className="btn-v-delete" onClick={() => alert('删除版本')}>删除版本</span>
                              </div>
                            </div>
                          ))}
                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ========== EDIT CRON MODAL ========== */}
      {showCronModal && editingCron && (
        <div className="cron-modal-overlay">
          <div className="cron-modal">
            <button className="cron-modal-close" onClick={() => setShowCronModal(false)}>×</button>
            <div>
              <h3 className="cron-modal-title">编辑定时任务</h3>
              <p className="cron-modal-subtitle">设置定时任务名称、图标、提示词和执行计划。</p>
            </div>

            <div className="cron-form-item">
              <input 
                className="cron-input-full" 
                value={editingCron.name} 
                onChange={e => setEditingCron({...editingCron, name: e.target.value})}
                placeholder="任务名称"
              />
            </div>

            <div className="cron-form-item">
              <label className="cron-form-label">任务图标</label>
              <div className="icon-selector-grid">
                {['📄', '⏱️', '📅', '🔍', '📊', '📰', '🤖', '💡', '🔔', '♻️', '🚀', '🔥', '🛠️', '📡', '📁', '🛡️'].map(emoji => (
                  <div 
                    key={emoji} 
                    className={`icon-opt ${editingCron.icon === emoji ? 'active' : ''}`}
                    onClick={() => setEditingCron({...editingCron, icon: emoji})}
                  >
                    {emoji}
                  </div>
                ))}
              </div>
            </div>

            <div className="cron-form-item">
              <label className="cron-form-label">提示词</label>
              <textarea 
                className="cron-prompt-area"
                value={editingCron.prompt}
                onChange={e => setEditingCron({...editingCron, prompt: e.target.value})}
                placeholder="请输入提示词..."
              />
              <div style={{ textAlign: 'right', fontSize: '12px', color: '#ccc', marginTop: '4px' }}>{editingCron.prompt.length}/20000</div>
            </div>

            <div className="cron-form-item">
              <label className="cron-form-label">定时计划</label>
              <select 
                className="cron-select" 
                value={editingCron.schedType || 'daily'} 
                onChange={e => setEditingCron({...editingCron, schedType: e.target.value})}
                style={{ marginBottom: 12 }}
              >
                <option value="daily">每日定时</option>
                <option value="custom">自定义间隔 (Cron)</option>
              </select>

              {editingCron.schedType === 'custom' ? (
                <div style={{ padding: '20px', border: '1px solid #f0f0f0', borderRadius: '16px' }}>
                  <div className="cron-form-label" style={{ fontSize: '12px', color: '#999' }}>执行频率</div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <span style={{ fontSize: '14px', color: '#666' }}>每隔</span>
                    <input 
                      type="number"
                      className="cron-time-val" 
                      style={{ width: '80px' }}
                      value={editingCron.frequency || 15} 
                      onChange={e => setEditingCron({...editingCron, frequency: e.target.value})}
                    />
                    <select 
                      className="cron-select" 
                      style={{ width: '100px', marginBottom: 0 }}
                      value={editingCron.unit || 'minutes'}
                      onChange={e => setEditingCron({...editingCron, unit: e.target.value})}
                    >
                      <option value="minutes">分钟</option>
                      <option value="hours">小时</option>
                    </select>
                    <span style={{ fontSize: '14px', color: '#666' }}>运行一次</span>
                  </div>
                  <div className="cron-cron-desc" style={{ marginTop: '16px' }}>
                    💡 提示: 该任务将以当前时间为起点，每 {editingCron.frequency || 15} {editingCron.unit === 'hours' ? '小时' : '分钟'} 自动触发。
                  </div>
                </div>
              ) : (
                <div style={{ padding: '24px', border: '1px solid #f0f0f0', borderRadius: '16px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
                  <div>
                    <div className="cron-form-label" style={{ fontSize: '12px', color: '#999' }}>执行时间</div>
                    <input type="time" className="cron-time-val" value={editingCron.time} onChange={e => setEditingCron({...editingCron, time: e.target.value})} />
                  </div>
                  <div>
                    <div className="cron-form-label" style={{ fontSize: '12px', color: '#999' }}>重复周期</div>
                    <div className="cron-week-btns">
                      {['周一', '周二', '周三', '周四', '周五', '周六', '周日'].map((day, idx) => (
                        <button 
                          key={idx} 
                          className={`cron-week-btn ${editingCron.days.includes(idx+1) ? 'active' : ''}`}
                          onClick={() => {
                            const newDays = editingCron.days.includes(idx+1) 
                              ? editingCron.days.filter(d => d !== idx+1)
                              : [...editingCron.days, idx+1];
                            setEditingCron({...editingCron, days: newDays});
                          }}
                        >
                          {day}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>

            <div className="cron-modal-footer">
              <div className="cron-footer-left">
                {/* Removed delete and pause buttons per request */}
              </div>
              <div className="cron-footer-right">
                <button className="btn-cancel" onClick={() => setShowCronModal(false)}>取消</button>
                <button className="btn-save" onClick={() => setShowCronModal(false)}>保存</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ========== RUN PROGRESS MODAL ========== */}
      {showRunProgress && (
        <div className="run-progress-overlay">
          <div className="run-progress-modal">
            <h3 className="run-progress-title">正在执行定时任务</h3>
            <div className="run-timeline">
              <div className={`run-step ${runStep >= 0 ? 'active' : ''} ${runStep > 0 ? 'done' : ''}`}>
                <div className={`run-step-icon ${runStep > 0 ? 'done' : 'active'}`}>
                  {runStep > 0 ? '✓' : '1'}
                </div>
                <div className="run-step-label">连接 Agent</div>
                <div className={`run-line ${runStep > 0 ? 'done' : ''}`} />
              </div>
              <div className={`run-step ${runStep >= 1 ? 'active' : ''} ${runStep > 1 ? 'done' : ''}`}>
                <div className={`run-step-icon ${runStep > 1 ? 'done' : (runStep === 1 ? 'active' : '')}`}>
                  {runStep > 1 ? '✓' : '2'}
                </div>
                <div className="run-step-label">运行定时任务</div>
                <div className={`run-line ${runStep > 1 ? 'done' : ''}`} />
              </div>
              <div className={`run-step ${runStep >= 2 ? 'active' : ''} ${runStep > 2 ? 'done' : ''}`}>
                <div className={`run-step-icon ${runStep >= 2 ? 'done' : ''}`}>
                  {runStep >= 2 ? '✓' : '3'}
                </div>
                <div className="run-step-label">执行成功</div>
              </div>
            </div>
            <p style={{ fontSize: '13px', color: '#999' }}>请稍候，任务正在处理中...</p>
          </div>
        </div>
      )}

      {/* ========== AI SKILL GENERATOR MODAL ========== */}
      {showAIGenModal && (
        <div className="ai-modal-overlay">
          <div className="ai-modal">
            <button className="cron-modal-close" onClick={() => setShowAIGenModal(false)}>×</button>
            <h3 className="ai-gen-title">✨ AI 生成智能技能</h3>
            <p style={{ color: '#64748b', fontSize: '14px', marginBottom: '24px' }}>输入你的需求描述，LLM 将自动为你构建、编写并配置该技能。</p>
            
            <textarea 
              className="ai-prompt-area"
              placeholder="例如: 帮我写一个能查询当前主要数字货币价格的工具..."
              rows={4}
              value={aiPrompt}
              onChange={e => setAiPrompt(e.target.value)}
              disabled={aiThinking}
            />
            
            <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'flex-end' }}>
              <button 
                className="btn-ai-gen" 
                onClick={handleAIGen}
                disabled={aiThinking || !aiPrompt.trim()}
              >
                {aiThinking ? '正在生成中...' : '开始生成'}
              </button>
            </div>

            {aiThinking && (
              <div className="ai-thinking">
                <div className="ai-loader" />
                <div style={{ fontSize: '15px', color: '#6366f1', fontWeight: 500 }}>AI 正在构思技能逻辑并编写代码...</div>
              </div>
            )}

            {generatedSkill && (
              <div className="ai-result-panel">
                <div className="ai-result-header">生成结果预览</div>
                <div className="ai-result-content">
                  <div style={{ display: 'flex', gap: '12px', alignItems: 'center', marginBottom: '16px' }}>
                    <div className="skill-icon-box">{generatedSkill.icon}</div>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: '16px' }}>{generatedSkill.name}</div>
                      <div style={{ fontSize: '13px', color: '#64748b' }}>{generatedSkill.description}</div>
                    </div>
                  </div>
                  <div className="code-preview">{generatedSkill.code}</div>
                </div>
                <div style={{ padding: '16px 24px', background: '#f8fafc', borderTop: '1px solid #e2e8f0', display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
                  <button className="btn-cancel" onClick={() => setGeneratedSkill(null)}>重新生成</button>
                  <button className="btn-save" onClick={addGeneratedSkill}>确认并添加技能</button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ========== AI SKILL GENERATOR MODAL ========== */}
      {showAIGenModal && (
        <div className="ai-modal-overlay">
          <div className="ai-modal">
            <button className="cron-modal-close" onClick={() => setShowAIGenModal(false)}>×</button>
            <h3 className="ai-gen-title">✨ AI 生成智能技能</h3>
            <p style={{ color: '#64748b', fontSize: '14px', marginBottom: '24px' }}>输入你的需求描述，LLM 将自动为你构建、编写并配置该技能。</p>
            
            <textarea 
              className="ai-prompt-area"
              placeholder="例如: 帮我写一个能查询当前主要数字货币价格的工具..."
              rows={4}
              value={aiPrompt}
              onChange={e => setAiPrompt(e.target.value)}
              disabled={aiThinking}
            />
            
            <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'flex-end' }}>
              <button 
                className="btn-ai-gen" 
                onClick={handleAIGen}
                disabled={aiThinking || !aiPrompt.trim()}
              >
                {aiThinking ? '正在生成中...' : '开始生成'}
              </button>
            </div>

            {aiThinking && (
              <div className="ai-thinking">
                <div className="ai-loader" />
                <div style={{ fontSize: '15px', color: '#6366f1', fontWeight: 500 }}>AI 正在构思技能逻辑并编写代码...</div>
              </div>
            )}

            {generatedSkill && (
              <div className="ai-result-panel">
                <div className="ai-result-header">生成结果预览</div>
                <div className="ai-result-content">
                  <div style={{ display: 'flex', gap: '12px', alignItems: 'center', marginBottom: '16px' }}>
                    <div className="skill-icon-box">{generatedSkill.icon}</div>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: '16px' }}>{generatedSkill.name}</div>
                      <div style={{ fontSize: '13px', color: '#64748b' }}>{generatedSkill.description}</div>
                    </div>
                  </div>
                  <div className="code-preview">{generatedSkill.code}</div>
                </div>
                <div style={{ padding: '16px 24px', background: '#f8fafc', borderTop: '1px solid #e2e8f0', display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
                  <button className="btn-cancel" onClick={() => setGeneratedSkill(null)}>重新生成</button>
                  <button className="btn-save" onClick={addGeneratedSkill}>确认并添加技能</button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ========== ACTION MENU (Dropdown) ========== */}
      {activeActionItem && activeActionItem.visible && (
        <div 
          className="webui-context-menu" 
          style={{ top: activeActionItem.y, left: activeActionItem.x }}
          onClick={(e) => e.stopPropagation()}
        >
          {activeActionItem.type === 'folder' ? (
            <>
              <div className="cm-item" onClick={() => alert('上传文件')}>📤 上传文件</div>
              <div className="cm-item" onClick={() => alert('新建文件夹')}>📁 新建子目录</div>
              <div className="cm-divider" />
              <div className={`cm-item ${['src', 'agentbase-react-demo'].includes(activeActionItem.item.name) ? 'disabled' : ''}`} onClick={() => !['src', 'agentbase-react-demo'].includes(activeActionItem.item.name) && alert('重命名')}>📝 重命名</div>
            </>
          ) : (
            <>
              <div className="cm-item" onClick={() => alert('下载文件')}>⬇️ 下载文件</div>
              <div className="cm-item" onClick={() => alert('重命名')}>📝 重命名</div>
              <div className="cm-divider" />
              <div className="cm-item" onClick={() => { setLinkFile(activeActionItem.item); setShowArtifactLinkModal(true); setActiveActionItem(null); }}>📦 存为制品 / 关联版本</div>
              <div className="cm-divider" />
              <div className="cm-item danger" onClick={() => alert('删除文件')}>🗑️ 删除文件</div>
            </>
          )}
        </div>
      )}

      {/* ========== ARTIFACT LINK MODAL ========== */}
      {showArtifactLinkModal && (
        <div className="ai-modal-overlay">
          <div className="ai-modal modal-artifact-link">
            <button className="cron-modal-close" onClick={() => setShowArtifactLinkModal(false)}>×</button>
            <h3>📦 同步为制品</h3>
            <p style={{ color: '#64748b', fontSize: '13px', marginBottom: '24px' }}>将文件 <strong>{linkFile?.name}</strong> 分发为制品或关联到现有制品版本。</p>
            
            <div className="link-type-tabs">
              <div className="link-type-tab active">关联到已有制品</div>
              <div className="link-type-tab" onClick={() => alert('切换到创建新制品')}>创建新制品</div>
            </div>

            <div className="artifact-select-list">
              {artifacts.map(art => (
                <div key={art.id} className="artifact-opt">
                  <div>
                    <div style={{ fontWeight: 600 }}>{art.name}</div>
                    <div style={{ fontSize: '11px', color: '#999' }}>当前版本: {art.versions[0]?.version}</div>
                  </div>
                  <button className="action-btn small" onClick={() => {
                    const newVersion = { id: `v${Date.now()}`, version: `v1.2.${art.versions.length}`, file: linkFile.name, time: '刚刚' };
                    setArtifacts(artifacts.map(a => a.id === art.id ? { ...a, versions: [newVersion, ...a.versions] } : a));
                    setShowArtifactLinkModal(false);
                  }}>选择</button>
                </div>
              ))}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '20px' }}>
              <button className="btn-cancel" onClick={() => setShowArtifactLinkModal(false)}>取消</button>
            </div>
          </div>
        </div>
      )}

      {/* ========== RIGHT: Workspace Files ========== */}
      <div className={`webui-workspace ${activeView === 'cron' || activeView === 'skills' || activeView === 'artifacts' || !showWorkspace ? 'hidden' : ''}`}>
        <div className="webui-workspace-header">
          <span>工作区文件</span>
        </div>
        <div className="webui-file-tree">
          {(agent.workspace?.files || []).length > 0 ? (
            renderFileTree(agent.workspace.files)
          ) : (
            <div className="webui-file-empty">暂无文件</div>
          )}
        </div>
      </div>
    </div>
  )
}
